### PR TITLE
Please create strings.xml SK

### PR DESCRIPTION
**Pull request by ja-som**

### CODE REVIEW

**Comment by loserskater** [comment]
You are quick! Still adding a few things. I'll make sure this is updated and merge before I release.

**Comment by ja-som** [comment]
I have a email notification :)
OK, I will update it ASAP when it's done ;)

**Comment by loserskater** [comment]
Ok I think that's the last commit. Should be at a good point to release.

**Comment by ja-som** [comment]
Last commit, added reboot strings.
Thanks :)

**Pull request merged**
